import React from 'react'
import Head from 'next/head'

function head() {
  return (
    <Head>
        <title>Service de Lavarropas Electrolux</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default head