import { Poppins } from '@next/font/google'
import styles from '@/styles/global.css'
import Head from 'next/head'


const font = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ['400', '500', '600', '700']
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout ({ children }) {
  return (
    <>
    <html className='appear bg-primary'>
      <Head>
        <title>Service Electrolux</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </html>
    <body className={`${font.variable}`}>
      
      <div className={`bg-primary ${styles.paddingX} ${styles.flexCenter}`}>
        <div className={`${styles.boxWidth}`}>
          <main>{children}</main>
      
        </div>
      </div>
    </body>
  </>
  )
}
